# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Telegram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Telegram
  pod 'Texture', '>= 2.0'

  target 'TelegramTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TelegramUITests' do
    # Pods for testing
  end

end
